CREATE DATABASE qlsv_project
GO

USE qlsv_project
GO

CREATE TABLE TAIKHOAN
(
	MaTk CHAR(10) PRIMARY KEY,
	TaiKhoan VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(50) NOT NULL,
	PhanLoai VARCHAR(10)	
)


CREATE TABLE CHUONGTRINH
(
		MaChuongTrinh CHAR(5) PRIMARY KEY,
		TenChuongTrinh NVARCHAR(50) NOT NULL,
)
CREATE TABLE KHOAHOC
(
		MaKhoaHoc CHAR(5) PRIMARY KEY,
		TenKhoaHoc NVARCHAR(50) NOT NULL,
		NamBatDau Date NOT NULL,
		NamKetThuc Date NOT NULL,
		MaChuongTrinh CHAR(5)		
		FOREIGN KEY(MaChuongTrinh) REFERENCES CHUONGTRINH(MaChuongTrinh)
)
CREATE TABLE KHOA
(
	MaKhoa CHAR(5) PRIMARY KEY,
	TenKhoa NVARCHAR(50) NOT NULL
)
 GO

 CREATE TABLE NGANH
 (
 MaNganh CHAR(5) PRIMARY KEY,
 TenNganh NVARCHAR(50) NOT NULL UNIQUE,
 MaKhoa  CHAR(5),
 FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)
 )



CREATE TABLE LOP 
(
		MaLop CHAR(5),
		TenLop NVARCHAR(50) NOT NULL UNIQUE,
		MaKhoaHoc CHAR(5),
		MaNganh CHAR(5),
		PRIMARY KEY(MaLop),
		FOREIGN KEY(MaNganh) REFERENCES NGANH(MaNganh),
		FOREIGN KEY(MaKhoaHoc) REFERENCES KHOAHOC(MaKhoaHoc)
)
GO


CREATE TABLE MON
(
		MaMon CHAR(5) PRIMARY KEY,
		TenMon NVARCHAR(50) NOT NULL UNIQUE,		
		SoTiet TINYINT,
		SoTinChi TINYINT,
		MaKhoa CHAR(5),
		FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)
)


CREATE TABLE GIAOVIEN
(
	MaGV CHAR(5) PRIMARY KEY,
	TenGV NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	GioiTinh BIT,
	SDT VARCHAR(10) UNIQUE,
	DiaChi NVARCHAR(50),
	MaKhoa CHAR(5),
	MaTk CHAR(10),
	FOREIGN KEY(MaTk) REFERENCES TAIKHOAN(MaTk),
	FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)

)

CREATE TABLE SINHVIEN
(
	MaSV CHAR(10) PRIMARY KEY,
	TenSV NVARCHAR(50) NOT NULL,
	NgaySinh DATE ,
	GioiTinh BIT ,
	DiaChi NVARCHAR(50),
	SDT VARCHAR(10) UNIQUE,
	NgayNhapHoc DATE,
	MaLop CHAR(5),
	MaTk CHAR(10),
	GhiChu NVARCHAR(50),
	FOREIGN KEY(MaLop) REFERENCES LOP(MaLop),
	FOREIGN KEY(MaTk) REFERENCES TAIKHOAN(MaTk)
)

CREATE TABLE LICHDAY
(
	MaGV CHAR(5) ,
	MaLop CHAR(5) ,
	MaMon CHAR(5) ,
	NgayDay DATE,
	SoTietDay TINYINT,
	CaDay BIT,
	Phong NVARCHAR(20) NOT NULL,
	GhiChu NVARCHAR(50),
	PRIMARY KEY(MaGV,MaLop,MaMon,NgayDay),
	FOREIGN KEY(MaMon) REFERENCES MON(MaMon),
	FOREIGN KEY(MaLop) REFERENCES LOP(MaLop),
	FOREIGN KEY(MaGV) REFERENCES GIAOVIEN(MaGV)
)




CREATE TABLE DIEM
(
	MaSV CHAR(10),
	MaMon CHAR(5),
	DiemTX1 FLOAT  DEFAULT 0,
	DiemTX2 FLOAT  DEFAULT 0,
	DiemKT1 FLOAT DEFAULT 0,
	DiemKT2 FLOAT DEFAULT 0,
	DiemThi FLOAT DEFAULT 0,
	LanThi TINYINT, 
	DiemTB FLOAT  DEFAULT 0,
	TrangThai NVARCHAR(20),
	GhiChu NVARCHAR(50),
	PRIMARY KEY(MaSV,MaMon),
	FOREIGN KEY(MaSV) REFERENCES SINHVIEN(MaSV),
	FOREIGN KEY(MaMon) REFERENCES MON(MaMon)

)
CREATE TABLE PHANCONG
(
	MaGV CHAR(5),
	MaLop CHAR(5) ,
	MaMon CHAR(5) ,
	ViTri NVARCHAR(20) NOT NULL,
	HocKi TINYINT NOT NULL,
	NamHoc DATE NOT NULL,
	PRIMARY KEY(MaGV,MaLop,MaMon),
	FOREIGN KEY(MaMon) REFERENCES MON(MaMon),
	FOREIGN KEY(MaLop) REFERENCES LOP(MaLop),
	FOREIGN KEY(MaGV) REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE DIEMDANH
(
	MaSV CHAR(10) NOT NULL,
    NgayDiemDanh DATETIME NOT NULL,
    DiemDanh BIT NOT NULL,
	GhiChu NVARCHAR(50),
	PRIMARY KEY(MaSV,NgayDiemDanh),
	FOREIGN KEY(MaSV) REFERENCES SINHVIEN(MaSV),
)
--CREATE TABLE CHAMCONG
--(
--	MaGV CHAR(10) NOT NULL,
--    NgayDiemDanh DATETIME NOT NULL,
--    DiemDanh BIT NOT NULL,
--	GhiChu NVARCHAR(50),
--	PRIMARY KEY(MaGV,NgayDiemDanh),
--	FOREIGN KEY(MaGV) REFERENCES GIAOVIEN(MaGV),
--)
--CREATE TABLE HOCPHI
--(
--MaSV VARCHAR(20) NOT NULL,
--HocKi BIT,
--NamHoc DATE,
--TienHocCoBan money,
--TienGiamHocPhi money,
--TienChinhThuc money,
--TrangThai BIT NOT NULL,
--GhiChu NVARCHAR(50),
--PRIMARY KEY(MaSV,HocKi,NamHoc)
--)

--CREATE TABLE LUONGGIAOVIEN
--(
--MaGV CHAR(10) NOT NULL,
--LuongCoBan MONEY,
--HeSoLuong TINYINT,
--MucThuongPhuCap MONEY,
--MucThuongThamNien MONEY,
--MucBHXH TINYINT,
--LuongChinhThuc MONEY
--PRIMARY KEY (MaGV,LuongChinhThuc),
--FOREIGN KEY(MaGV) REFERENCES GIAOVIEN(MaGV)
--)
--CREATE INDEX LOP_INDEX
--ON LOP(MaKhoa,MaLop)
--GO

CREATE INDEX SINHVIEN_INDEX
ON SINHVIEN(MaLop,MaSV)
GO

CREATE INDEX GIAOVIEN_INDEX
ON GIAOVIEN(MaKhoa,MaGV)
GO
CREATE INDEX DIEM_INDEX
ON DIEM(MaMon,MaSV)
GO

CREATE PROCEDURE REMOVEKHOA(@MaKhoa CHAR(5))
AS
BEGIN
UPDATE NGANH SET MaKhoa= NULL WHERE MaKhoa= @MaKhoa
UPDATE MON SET MaKhoa= NULL WHERE MaKhoa= @MaKhoa
UPDATE GIAOVIEN SET MaKhoa= NULL WHERE MaKhoa= @MaKhoa
DELETE FROM KHOA WHERE MaKhoa= @MaKhoa
END
GO


CREATE PROCEDURE REMOVENGANH(@MaNganh CHAR(5))
AS
BEGIN
UPDATE LOP SET MaNganh= NULL WHERE MaNganh= @MaNganh
DELETE FROM NGANH WHERE MaNganh= @MaNganh
END
GO

CREATE PROCEDURE REMOVELOP(@MaLop CHAR(5))
AS
BEGIN
UPDATE PHANCONG SET MaLop= NULL WHERE MaLop= @MaLop
UPDATE LICHDAY SET MaLop= NULL WHERE MaLop= @MaLop
UPDATE SINHVIEN SET MaLop= NULL WHERE MaLop= @MaLop

DELETE FROM LOP WHERE MaLop= @MaLop
END
GO

CREATE SEQUENCE SE_MAKHOA
START WITH 100
INCREMENT BY 1

CREATE SEQUENCE SE_MANGANH
START WITH 100
INCREMENT BY 1

CREATE SEQUENCE SE_MALOP
START WITH 100
INCREMENT BY 1

CREATE SEQUENCE SE_MASV
START WITH 10000000
INCREMENT BY 1

CREATE PROCEDURE INSERTSV
	@MaSV CHAR(10),
	@TenSV NVARCHAR(50),
	@NgaySinh DATE ,
	@GioiTinh BIT ,
	@DiaChi NVARCHAR(50),
	@SDT VARCHAR(10),
	@NgayNhapHoc DATE,
	@MaLop CHAR(5),
	@GhiChu NVARCHAR(50)

	
AS
BEGIN

DECLARE @IDTK CHAR(10);
SET @IDTK='TK'+@MaSV;
INSERT INTO TAIKHOAN VALUES(@IDTK,@MaSV,'123','sv');
INSERT INTO SINHVIEN VALUES(@MaSV,@TenSV,@NgaySinh,@GioiTinh,@DiaChi,@SDT,@NgayNhapHoc,@MaLop,@IDTK,@GhiChu);
END
GO 


CREATE PROCEDURE DELSV
@MaSV CHAR(10)
AS
BEGIN
DECLARE @IDTK CHAR(10);
SELECT @IDTK=MaTk FROM SINHVIEN WHERE MaSV=@MaSV;
DELETE FROM SINHVIEN WHERE MaSV=@MaSV;
DELETE FROM TAIKHOAN WHERE MaTk=@IDTK;

END
GO
EXECUTE DELSV 'SV1332'
SELECT * FROM SINHVIEN
SELECT * FROM TAIKHOAN
EXECUTE DELSV 'SV1019'
SELECT Matk,PhanLoai FROM TAIKHOAN WHERE TaiKhoan='admin' AND MatKhau='12345'
INSERT INTO TAIKHOAN VALUES('TK11111112','admin','123','admin')
INSERT INTO CHUONGTRINH VALUES('CT100',N'Cao Đẳng');
INSERT INTO KHOAHOC VALUES('K1000',N'CD45CNTT','2023-01-01','2023-01-01','CT100');
SELECT ROW_NUMBER() OVER( ORDER BY MaNganh) AS STT,MaNganh,TenNganh,KHOA.MaKhoa,KHOA.TenKhoa,NGANH.NamBatDau FROM NGANH LEFT JOIN KHOA ON NGANH.MaKhoa=KHOA.MaKhoa


SELECT ROW_NUMBER() OVER( ORDER BY MaLop) AS STT,MaLop,TenLop,KHOAHOC.TenKhoaHoc,NGANH.TenNganh,LOP.GhiChu FROM LOP  LEFT JOIN NGANH ON LOP.MaNganh=NGANH.MaNganh LEFT JOIN KHOAHOC ON LOP.MaKhoaHoc=KHOAHOC.MaKhoaHoc;
GO 